version: "3.4"
services:
  service:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    working_dir: &PROJECT_ROOT_DIR /app
    # linux permissions / vscode support: we must explicitly run as the development user
    user: development
    volumes:
      # mount working directory
      # https://code.visualstudio.com/docs/remote/containers-advanced#_update-the-mount-consistency-to-delegated-for-macos
      # https://docs.docker.com/docker-for-mac/osxfs-caching/#delegated
      # the container’s view is authoritative (permit delays before updates on the container appear in the host)
      - .:/app:delegated

      # mount cached go pkg downloads
      - go-pkg:/go/pkg

      # speed up tmp dirs in working directory by using separate volumes (not the host's filesystem)
      - workdir-api-tmp:/app/api/tmp
      - workdir-bin:/app/bin
      - workdir-tmp:/app/tmp

      # mount cached vscode container extensions
      # https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
      - vscode-extensions:/home/development/.vscode-server/extensions
      - vscode-extensions-insiders:/home/development/.vscode-server-insiders/extensions

    environment:
      PROJECT_ROOT_DIR: *PROJECT_ROOT_DIR
      SERVER_LOGGER_PRETTY_PRINT_CONSOLE: "true"

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command:
      - /bin/sh
      - -c
      - |
        sudo chown -R development:development /app/api/tmp
        sudo chown -R development:development /app/bin
        sudo chown -R development:development /app/tmp
        chmod +x /app/rksh
        git config --global --add safe.directory /app
        while sleep 1000; do :; done

volumes:
  # go: go mod cached downloads
  go-pkg:

  # tmp dirs in workdir
  workdir-api-tmp:
  workdir-bin:
  workdir-tmp:

  # vscode: Avoiding extension reinstalls on container rebuild
  # https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
  vscode-extensions:
  vscode-extensions-insiders:
